spring.application.name=omr-server

spring.datasource.url=jdbc:postgresql://localhost:5432/omr_server_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

server.address=192.168.2.131
server.port=8001
logging.level.org.springframework.security=DEBUG
server.servlet.session.persistent=false